/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InternRouteImport } from './routes/intern'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorIndexRouteImport } from './routes/mentor.index'
import { Route as InternIndexRouteImport } from './routes/intern.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MentorQueueRouteImport } from './routes/mentor.queue'
import { Route as MentorInternsRouteImport } from './routes/mentor.interns'
import { Route as MentorHistoryRouteImport } from './routes/mentor.history'
import { Route as MentorCreateInternRouteImport } from './routes/mentor.create-intern'
import { Route as InternTasksRouteImport } from './routes/intern.tasks'
import { Route as InternSubmissionsRouteImport } from './routes/intern.submissions'
import { Route as InternProfileRouteImport } from './routes/intern.profile'
import { Route as InternFeedbackRouteImport } from './routes/intern.feedback'
import { Route as InternCertificateRouteImport } from './routes/intern.certificate'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'

const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InternRoute = InternRouteImport.update({
  id: '/intern',
  path: '/intern',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorIndexRoute = MentorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorRoute,
} as any)
const InternIndexRoute = InternIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InternRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MentorQueueRoute = MentorQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => MentorRoute,
} as any)
const MentorInternsRoute = MentorInternsRouteImport.update({
  id: '/interns',
  path: '/interns',
  getParentRoute: () => MentorRoute,
} as any)
const MentorHistoryRoute = MentorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MentorRoute,
} as any)
const MentorCreateInternRoute = MentorCreateInternRouteImport.update({
  id: '/create-intern',
  path: '/create-intern',
  getParentRoute: () => MentorRoute,
} as any)
const InternTasksRoute = InternTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => InternRoute,
} as any)
const InternSubmissionsRoute = InternSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => InternRoute,
} as any)
const InternProfileRoute = InternProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InternRoute,
} as any)
const InternFeedbackRoute = InternFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => InternRoute,
} as any)
const InternCertificateRoute = InternCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => InternRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/intern': typeof InternRouteWithChildren
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/intern/certificate': typeof InternCertificateRoute
  '/intern/feedback': typeof InternFeedbackRoute
  '/intern/profile': typeof InternProfileRoute
  '/intern/submissions': typeof InternSubmissionsRoute
  '/intern/tasks': typeof InternTasksRoute
  '/mentor/create-intern': typeof MentorCreateInternRoute
  '/mentor/history': typeof MentorHistoryRoute
  '/mentor/interns': typeof MentorInternsRoute
  '/mentor/queue': typeof MentorQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/intern/': typeof InternIndexRoute
  '/mentor/': typeof MentorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/intern/certificate': typeof InternCertificateRoute
  '/intern/feedback': typeof InternFeedbackRoute
  '/intern/profile': typeof InternProfileRoute
  '/intern/submissions': typeof InternSubmissionsRoute
  '/intern/tasks': typeof InternTasksRoute
  '/mentor/create-intern': typeof MentorCreateInternRoute
  '/mentor/history': typeof MentorHistoryRoute
  '/mentor/interns': typeof MentorInternsRoute
  '/mentor/queue': typeof MentorQueueRoute
  '/admin': typeof AdminIndexRoute
  '/intern': typeof InternIndexRoute
  '/mentor': typeof MentorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/intern': typeof InternRouteWithChildren
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/intern/certificate': typeof InternCertificateRoute
  '/intern/feedback': typeof InternFeedbackRoute
  '/intern/profile': typeof InternProfileRoute
  '/intern/submissions': typeof InternSubmissionsRoute
  '/intern/tasks': typeof InternTasksRoute
  '/mentor/create-intern': typeof MentorCreateInternRoute
  '/mentor/history': typeof MentorHistoryRoute
  '/mentor/interns': typeof MentorInternsRoute
  '/mentor/queue': typeof MentorQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/intern/': typeof InternIndexRoute
  '/mentor/': typeof MentorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/intern'
    | '/login'
    | '/mentor'
    | '/admin/assignments'
    | '/admin/programs'
    | '/admin/tasks'
    | '/admin/users'
    | '/intern/certificate'
    | '/intern/feedback'
    | '/intern/profile'
    | '/intern/submissions'
    | '/intern/tasks'
    | '/mentor/create-intern'
    | '/mentor/history'
    | '/mentor/interns'
    | '/mentor/queue'
    | '/admin/'
    | '/intern/'
    | '/mentor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/assignments'
    | '/admin/programs'
    | '/admin/tasks'
    | '/admin/users'
    | '/intern/certificate'
    | '/intern/feedback'
    | '/intern/profile'
    | '/intern/submissions'
    | '/intern/tasks'
    | '/mentor/create-intern'
    | '/mentor/history'
    | '/mentor/interns'
    | '/mentor/queue'
    | '/admin'
    | '/intern'
    | '/mentor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/intern'
    | '/login'
    | '/mentor'
    | '/admin/assignments'
    | '/admin/programs'
    | '/admin/tasks'
    | '/admin/users'
    | '/intern/certificate'
    | '/intern/feedback'
    | '/intern/profile'
    | '/intern/submissions'
    | '/intern/tasks'
    | '/mentor/create-intern'
    | '/mentor/history'
    | '/mentor/interns'
    | '/mentor/queue'
    | '/admin/'
    | '/intern/'
    | '/mentor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InternRoute: typeof InternRouteWithChildren
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern': {
      id: '/intern'
      path: '/intern'
      fullPath: '/intern'
      preLoaderRoute: typeof InternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/': {
      id: '/mentor/'
      path: '/'
      fullPath: '/mentor/'
      preLoaderRoute: typeof MentorIndexRouteImport
      parentRoute: typeof MentorRoute
    }
    '/intern/': {
      id: '/intern/'
      path: '/'
      fullPath: '/intern/'
      preLoaderRoute: typeof InternIndexRouteImport
      parentRoute: typeof InternRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mentor/queue': {
      id: '/mentor/queue'
      path: '/queue'
      fullPath: '/mentor/queue'
      preLoaderRoute: typeof MentorQueueRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/interns': {
      id: '/mentor/interns'
      path: '/interns'
      fullPath: '/mentor/interns'
      preLoaderRoute: typeof MentorInternsRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/history': {
      id: '/mentor/history'
      path: '/history'
      fullPath: '/mentor/history'
      preLoaderRoute: typeof MentorHistoryRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/create-intern': {
      id: '/mentor/create-intern'
      path: '/create-intern'
      fullPath: '/mentor/create-intern'
      preLoaderRoute: typeof MentorCreateInternRouteImport
      parentRoute: typeof MentorRoute
    }
    '/intern/tasks': {
      id: '/intern/tasks'
      path: '/tasks'
      fullPath: '/intern/tasks'
      preLoaderRoute: typeof InternTasksRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/submissions': {
      id: '/intern/submissions'
      path: '/submissions'
      fullPath: '/intern/submissions'
      preLoaderRoute: typeof InternSubmissionsRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/profile': {
      id: '/intern/profile'
      path: '/profile'
      fullPath: '/intern/profile'
      preLoaderRoute: typeof InternProfileRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/feedback': {
      id: '/intern/feedback'
      path: '/feedback'
      fullPath: '/intern/feedback'
      preLoaderRoute: typeof InternFeedbackRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/certificate': {
      id: '/intern/certificate'
      path: '/certificate'
      fullPath: '/intern/certificate'
      preLoaderRoute: typeof InternCertificateRouteImport
      parentRoute: typeof InternRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InternRouteChildren {
  InternCertificateRoute: typeof InternCertificateRoute
  InternFeedbackRoute: typeof InternFeedbackRoute
  InternProfileRoute: typeof InternProfileRoute
  InternSubmissionsRoute: typeof InternSubmissionsRoute
  InternTasksRoute: typeof InternTasksRoute
  InternIndexRoute: typeof InternIndexRoute
}

const InternRouteChildren: InternRouteChildren = {
  InternCertificateRoute: InternCertificateRoute,
  InternFeedbackRoute: InternFeedbackRoute,
  InternProfileRoute: InternProfileRoute,
  InternSubmissionsRoute: InternSubmissionsRoute,
  InternTasksRoute: InternTasksRoute,
  InternIndexRoute: InternIndexRoute,
}

const InternRouteWithChildren =
  InternRoute._addFileChildren(InternRouteChildren)

interface MentorRouteChildren {
  MentorCreateInternRoute: typeof MentorCreateInternRoute
  MentorHistoryRoute: typeof MentorHistoryRoute
  MentorInternsRoute: typeof MentorInternsRoute
  MentorQueueRoute: typeof MentorQueueRoute
  MentorIndexRoute: typeof MentorIndexRoute
}

const MentorRouteChildren: MentorRouteChildren = {
  MentorCreateInternRoute: MentorCreateInternRoute,
  MentorHistoryRoute: MentorHistoryRoute,
  MentorInternsRoute: MentorInternsRoute,
  MentorQueueRoute: MentorQueueRoute,
  MentorIndexRoute: MentorIndexRoute,
}

const MentorRouteWithChildren =
  MentorRoute._addFileChildren(MentorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InternRoute: InternRouteWithChildren,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
